[workspace]
members = ["mopro-ffi", "cli", "circom-prover", "tests"]
resolver = "2"

[workspace.dependencies]
rust-witness = "0.1"

uniffi = { version = "=0.31.0" }
uniffi_bindgen = { version = "=0.31.0" }