[package]
name = "mopro-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["wasmer/dylib"]
dylib = [] # NOTE: can probably remove this if we use env config instead
gpu-benchmarks = []
calc-native-witness = [
    "witness",
] # experimental feature to calculate witness with witness graph
build-native-witness = [
    "witness/build-witness",
] # only enable build-native-witness feature when building the witness graph

[dependencies]
ark-circom = { git = "https://github.com/vivianjeng/circom-compat-wasm3.git" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ark-serialize = { version = "=0.4.1", features = ["derive"] }
num-bigint = { version = "=0.4.3", default-features = false, features = [
    "rand",
] }
instant = "0.1"
wasmer = { git = "https://github.com/oskarth/wasmer.git", rev = "09c7070" }
once_cell = "1.8"
ruint = { version = "1.10.0", features = ["rand", "serde", "ark-ff-04"] }

# ZKP generation
ark-ec = { version = "=0.4.1", default-features = false, features = [
    "parallel",
] }
ark-crypto-primitives = { version = "=0.4.0" }
ark-std = { version = "=0.4.0", default-features = false, features = [
    "parallel",
] }
ark-bn254 = { version = "=0.4.0" }
ark-groth16 = { version = "=0.4.0", default-features = false, features = [
    "parallel",
] }
ark-relations = { version = "0.4", default-features = false }
ark-zkey = { path = "../ark-zkey" }
witness = { git = "https://github.com/philsippl/circom-witness-rs.git", optional = true }

# Error handling
thiserror = "=1.0.39"
color-eyre = "=0.6.2"
criterion = "=0.3.6"

[build-dependencies]
color-eyre = "0.6"
enumset = "1.0.8"
wasmer = { git = "https://github.com/oskarth/wasmer.git", rev = "09c7070" }
toml = "0.8"
serde = "1.0"
serde_derive = "1.0"
witness = { git = "https://github.com/philsippl/circom-witness-rs.git", optional = true }

[[bin]]
name = "generate_benchmark_report"
path = "src/middleware/gpu_explorations/bin/generate_benchmark_report.rs"
